source/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import RegisterView, UserProfileView, UpdateUserView, UserPasswordChangeView

app_name = 'accounts'

urlpatterns = [
    path("<int:pk>/", UserProfileView.as_view(), name="user_profile"),
    path('login/', LoginView.as_view(template_name="profile/login.html"), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('registration/', RegisterView.as_view(), name="registration"),
    path("update/<int:pk>/", UpdateUserView.as_view(), name="update_user"),
    path("change_password/", UserPasswordChangeView.as_view(), name="change_password")
]

source/api/urls.py
from django.urls import path
from api import views

app_name = "api"

urlpatterns = [
    path('quotes/', views.QuoteListAPIView.as_view(), name='quote_list'),
    path('quote/create/', views.QuoteCreateAPIView.as_view(), name='quote_create'),
    path('quote/<int:pk>/detail/', views.QuoteDetailAPIView.as_view(), name='quote_detail'),
    path('quote/<int:pk>/update/', views.QuoteUpdateAPIView.as_view(), name='quote_update'),
    path('quote/<int:pk>/delete/', views.QuoteDeleteAPIView.as_view(), name='quote_delete'),
    path('quote/<int:pk>/rate/', views.QuoteRateAPIView.as_view(), name='quote_rate'),
]

source/lab72/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('quote.urls')),
    path('api/', include('api.urls'))
]

source/quote/urls.py
from django.urls import path

from quote.views import IndexView, QuoteDetailView

app_name = 'quote'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('<int:pk>/', QuoteDetailView.as_view(), name='quote_detail_view'),
]

source/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>{% block title %}Quote{% endblock %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>
{% csrf_token %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">

        <a class="navbar-brand" href={% url 'quote:index' %}>Home</a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">

                {% block nav %}{% endblock %}


                {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}?next={{ request.get_full_path }}">Вход</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:registration' %}?next={{ request.get_full_path }}">Регистрация</a>
                    </li>

                {% else %}
                    <li class="nav-item">
                        <a class="nav-link"
                           href="{% url 'accounts:user_profile' request.user.pk %}">Профиль</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link"
                           href="{% url 'accounts:logout' %}?next={{ request.get_full_path }}">Выход</a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="#" onclick="showForm()">Добавить</a>
                </li>
            </ul>
        </div>

    </div>
</nav>

<div id="content" class="container">
    {% block content %}{% endblock %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
{% block scripts %}{% endblock %}
</body>
</html>

source/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Главная{% endblock %}
{% block content %}
    <div id="quotes-container">
    <h3>Цитаты</h3>
    {% for quote in quotes %}
        <div class="row">
            <p>&quot;{{ quote.text }}&quot;</p>
            <p>Дата добавления: {{ quote.created_at }}</p>
            <p>Ссылка: <a href="{% url 'quote:quote_detail_view' quote.pk %}">Детальный просмотр</a></p>
            <p>Рейтинг: {{ quote.rating }}</p>
        </div>
        <hr>
    {% endfor %}
    </div>
    <div id="form-container" class="row" style="display: none">
        <form id="quote-form" method="post" action="{% url 'api:quote_create' %}">
            <label>Текст:
                <input type="text" name="text">
            </label>
            <br>
            <label>Имя пользователя:
                <input type="text" name="user_name">
            </label>
            <br>
            <label>Эл. почта:
                <input type="text" name="email">
            </label>
            <br>
            <button type="submit">Сохранить</button>
            <br>
            <button onclick="hideForm()">Отмена</button>
        </form>
    </div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/script.js' %}"></script>
{% endblock %}

source/templates/quote_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Детали{% endblock %}
{% block content %}
    <div id="quotes-container">
    <h3>Цитата</h3>
        <div class="row">
            <p>&quot;{{ quote.text }}&quot;</p>
            <p>Пользователь: {{ quote.user_name }}</p>
            <p>Дата добавления: {{ quote.created_at }}</p>
            <p>Эл. почта: {{ quote.email }}</p>
            <p>Рейтинг: {{ quote.rating }}</p>
        </div>
        <hr>
    </div>
{% endblock %}