source/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import RegisterView, UserProfileView, UpdateUserView, UserPasswordChangeView

app_name = 'accounts'

urlpatterns = [
    path("<int:pk>/", UserProfileView.as_view(), name="user_profile"),
    path('login/', LoginView.as_view(template_name="profile/login.html"), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('registration/', RegisterView.as_view(), name="registration"),
    path("update/<int:pk>/", UpdateUserView.as_view(), name="update_user"),
    path("change_password/", UserPasswordChangeView.as_view(), name="change_password")
]

source/api/urls.py
from django.urls import path
from api import views

app_name = "api"

urlpatterns = [
    path('quotes/', views.QuoteListAPIView.as_view(), name='quote_list'),
    path('quote/create/', views.QuoteCreateAPIView.as_view(), name='quote_create'),
    path('quote/<int:pk>/detail/', views.QuoteDetailAPIView.as_view(), name='quote_detail'),
    path('quote/<int:pk>/update/', views.QuoteUpdateAPIView.as_view(), name='quote_update'),
    path('quote/<int:pk>/delete/', views.QuoteDeleteAPIView.as_view(), name='quote_delete'),
    path('quote/<int:pk>/rate/', views.QuoteRateAPIView.as_view(), name='quote_rate'),
]

source/lab72/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('quote.urls')),
    path('api/', include('api.urls'))
]

source/templates/profile/login.html
{% extends 'base.html' %}

{% block title %}Вход{% endblock %}

{% block content %}
    <h1>Вход</h1>
    <form method="post" class="text-center ms-auto me-auto w-50">
        {% csrf_token %}
        {% if has_error %}
            <p class="text-danger">Неверное имя пользователя или пароль.</p>
        {% endif %}
        <div class="form-group">
            <label for="username" class="form-label">Имя пользователя:</label>
            <input type="text" name="username" id="username" class="form-control">
        </div>
        <div class="form-group">
            <label for="password" class="form-label">Пароль:</label>
            <input type="password" name="password" id="password" class="form-control">
        </div>

        <button class="mt-3 btn btn-primary" type="submit">Войти</button>
    </form>
{% endblock %}

source/templates/profile/profile.html
{% extends "base.html" %}

{% block nav %}
    {% if user_object == user %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:update_user' user.pk %}">Редактирвоать профиль</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:change_password' %}">Изменить пароль</a>
        </li>
    {% endif %}
{% endblock %}

{% block content %}
    <h1>Профиль пользователя {{ user_object.username }}</h1>
    <p><strong>Почта: </strong>{{ user_object.email|default:"Не указана" }}</p>
    <p><strong>Дата рождения: </strong>{{ user_object.profile.birth_date|date:'d.m.Y'|default:"Не указана" }}</p>
    <p><strong>Фамилия: </strong>{{ user_object.last_name|default:"Не указана" }}</p>
    <p><strong>Имя: </strong>{{ user_object.first_name|default:"Не указанo" }}</p>

    {% if user_object.profile.avatar %}
        <img src="{{ user_object.profile.avatar.url }}" alt="user avatar">
    {% endif %}

    <h3>Альбомы</h3><br>
    <div class="row">
        {% for a in user_object.albums.all %}
            <div class="col-md-3">
                <a href="{% url 'gallery:album_detail' a.pk %}">Название: d{{ a.title }}</a>
                <br>
                <p>Описание: {{ a.description }}</p>
            </div>
        {% endfor %}
    </div>
    <h3>Фото</h3><br>
    <div class="row">
        {% for p in user_object.photos.all %}
            {% if not p.is_private or request.user == p.user %}
                <div class="col-md-3">
                    <img src="{{ p.image.url }}" style=" width: 10rem; height:
                10rem; background-repeat: no-repeat;" alt="">
                    <br>
                    <a href="{% url 'gallery:photo_detail' p.id %}">{{ p.description }}</a>
                </div>
            {% endif %}
        {% endfor %}
    </div>

{% endblock content %}

source/templates/profile/registration.html
{% extends 'base.html' %}

{% block title %}Регистрация{% endblock %}

{% block content %}
    <h1>Регистрация</h1>
    <form method="post">
        {% include "partial/form.html" with button_text="Зарегистрироваться" %}
    </form>
{% endblock %}

source/templates/profile/update_profile.html
{% extends "base.html" %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include "partial/form.html" with fields_only=True %}
        {% include "partial/form.html" with fields_only=True form=profile_form %}
        <input type="submit" class="btn btn-danger" value={{ button_text|default:"Сохранить" }} >
    </form>
{% endblock content %}

source/templates/profile/user_password_change.html
{% extends 'base.html' %}


{% block title %}Смена пароля{% endblock %}


{% block nav %}
    <li class="nav-item">
        <a class="nav-link" href="{% url "accounts:user_profile" user.pk %}">Назад</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url "accounts:update_user" user.pk %}">Редактировать профиль</a>
    </li>
{% endblock nav %}


{% block content %}

    <h1>Смена пароля</h1>

    <form method="POST">
        {% include 'partial/form.html' %}
    </form>

{% endblock %}